/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISponsorWhitelistControl, ISponsorWhitelistControlInterface } from "../../interfaces/ISponsorWhitelistControl.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contractAddr",
        "type": "address"
      }
    ],
    "name": "setSponsorForCollateral",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contractAddr",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "upperBound",
        "type": "uint256"
      }
    ],
    "name": "setSponsorForGas",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ISponsorWhitelistControl__factory {
    static readonly abi = _abi;
    static createInterface(): ISponsorWhitelistControlInterface {
      return new Interface(_abi) as ISponsorWhitelistControlInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISponsorWhitelistControl {
      return new Contract(address, _abi, runner) as unknown as ISponsorWhitelistControl;
    }
  }
  