/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace GigShield {
      
    export type MilestoneStruct = {description: string, amount: BigNumberish, status: BigNumberish, submittedAt: BigNumberish, autoReleasePaused: boolean}

    export type MilestoneStructOutput = [description: string, amount: bigint, status: bigint, submittedAt: bigint, autoReleasePaused: boolean] & {description: string, amount: bigint, status: bigint, submittedAt: bigint, autoReleasePaused: boolean }
  
    }

  export interface GigShieldInterface extends Interface {
    getFunction(nameOrSignature: "AUTO_RELEASE_PERIOD" | "DISPUTE_RESPONSE_PERIOD" | "MAX_ARBITRATORS_PER_DISPUTE" | "MAX_MILESTONES" | "approveMilestone" | "arbitratorPool" | "assignArbitrators" | "autoReleaseTimeRemaining" | "canAutoRelease" | "createProject" | "depositEscrow" | "disputeCount" | "disputes" | "enableSponsorship" | "fileDispute" | "getArbitratorPoolSize" | "getDisputeArbitrators" | "getProjectMilestones" | "hasVoted" | "isArbitrator" | "milestoneDispute" | "milestones" | "owner" | "pauseAutoRelease" | "projectCount" | "projects" | "registerArbitrator" | "removeArbitrator" | "renounceOwnership" | "requestRevision" | "submitDisputeResponse" | "submitMilestone" | "transferOwnership" | "triggerAutoRelease" | "voteOnDispute"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArbitratorRegistered" | "ArbitratorRemoved" | "ArbitratorVoted" | "ArbitratorsAssigned" | "AutoReleasePaused" | "AutoReleaseTriggered" | "DisputeFiled" | "DisputeResolved" | "DisputeResponseSubmitted" | "EscrowDeposited" | "MilestoneApproved" | "MilestoneRevisionRequested" | "MilestoneSubmitted" | "OwnershipTransferred" | "ProjectCreated" | "SponsorshipEnabled"): EventFragment;

    encodeFunctionData(functionFragment: 'AUTO_RELEASE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'DISPUTE_RESPONSE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_ARBITRATORS_PER_DISPUTE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MILESTONES', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'arbitratorPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'assignArbitrators', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'autoReleaseTimeRemaining', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'canAutoRelease', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [AddressLike, string, string, AddressLike, string[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'depositEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'disputeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'disputes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'enableSponsorship', values?: undefined): string;
encodeFunctionData(functionFragment: 'fileDispute', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getArbitratorPoolSize', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDisputeArbitrators', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProjectMilestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'milestoneDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'milestones', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseAutoRelease', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'projectCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeArbitrator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestRevision', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitDisputeResponse', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'submitMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'triggerAutoRelease', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'voteOnDispute', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'AUTO_RELEASE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DISPUTE_RESPONSE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_ARBITRATORS_PER_DISPUTE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MILESTONES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arbitratorPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignArbitrators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoReleaseTimeRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canAutoRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enableSponsorship', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fileDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArbitratorPoolSize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDisputeArbitrators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestoneDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseAutoRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRevision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitDisputeResponse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'triggerAutoRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnDispute', data: BytesLike): Result;
  }

  
    export namespace ArbitratorRegisteredEvent {
      export type InputTuple = [arbitrator: AddressLike];
      export type OutputTuple = [arbitrator: string];
      export interface OutputObject {arbitrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArbitratorRemovedEvent {
      export type InputTuple = [arbitrator: AddressLike];
      export type OutputTuple = [arbitrator: string];
      export interface OutputObject {arbitrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArbitratorVotedEvent {
      export type InputTuple = [disputeId: BigNumberish, arbitrator: AddressLike];
      export type OutputTuple = [disputeId: bigint, arbitrator: string];
      export interface OutputObject {disputeId: bigint, arbitrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArbitratorsAssignedEvent {
      export type InputTuple = [disputeId: BigNumberish, arbitrators: [AddressLike, AddressLike, AddressLike]];
      export type OutputTuple = [disputeId: bigint, arbitrators: [string, string, string]];
      export interface OutputObject {disputeId: bigint, arbitrators: [string, string, string] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutoReleasePausedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutoReleaseTriggeredEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint, amount: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeFiledEvent {
      export type InputTuple = [disputeId: BigNumberish, projectId: BigNumberish, milestoneIndex: BigNumberish, filedBy: AddressLike];
      export type OutputTuple = [disputeId: bigint, projectId: bigint, milestoneIndex: bigint, filedBy: string];
      export interface OutputObject {disputeId: bigint, projectId: bigint, milestoneIndex: bigint, filedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [disputeId: BigNumberish, outcome: BigNumberish];
      export type OutputTuple = [disputeId: bigint, outcome: bigint];
      export interface OutputObject {disputeId: bigint, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResponseSubmittedEvent {
      export type InputTuple = [disputeId: BigNumberish, responder: AddressLike];
      export type OutputTuple = [disputeId: bigint, responder: string];
      export interface OutputObject {disputeId: bigint, responder: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowDepositedEvent {
      export type InputTuple = [projectId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, amount: bigint];
      export interface OutputObject {projectId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint, amount: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRevisionRequestedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneSubmittedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, client: AddressLike, freelancer: AddressLike, name: string, totalAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, client: string, freelancer: string, name: string, totalAmount: bigint];
      export interface OutputObject {projectId: bigint, client: string, freelancer: string, name: string, totalAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SponsorshipEnabledEvent {
      export type InputTuple = [gasAmount: BigNumberish, collateralAmount: BigNumberish];
      export type OutputTuple = [gasAmount: bigint, collateralAmount: bigint];
      export interface OutputObject {gasAmount: bigint, collateralAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GigShield extends BaseContract {
    
    connect(runner?: ContractRunner | null): GigShield;
    waitForDeployment(): Promise<this>;

    interface: GigShieldInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    AUTO_RELEASE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DISPUTE_RESPONSE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_ARBITRATORS_PER_DISPUTE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MILESTONES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approveMilestone: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    arbitratorPool: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    assignArbitrators: TypedContractMethod<
      [_disputeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autoReleaseTimeRemaining: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    canAutoRelease: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    createProject: TypedContractMethod<
      [_freelancer: AddressLike, _name: string, _description: string, _paymentToken: AddressLike, _milestoneDescriptions: string[], _milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    depositEscrow: TypedContractMethod<
      [_projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    disputeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    disputes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {projectId: bigint, milestoneIndex: bigint, status: bigint, filedBy: string, clientEvidence: string, freelancerEvidence: string, filedAt: bigint, responseDeadline: bigint, votesForFreelancer: bigint, votesForClient: bigint, totalVotes: bigint, outcome: bigint }],
      'view'
    >
    

    
    enableSponsorship: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    fileDispute: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, _evidence: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getArbitratorPoolSize: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDisputeArbitrators: TypedContractMethod<
      [_disputeId: BigNumberish, ],
      [[string, string, string]],
      'view'
    >
    

    
    getProjectMilestones: TypedContractMethod<
      [_projectId: BigNumberish, ],
      [GigShield.MilestoneStructOutput[]],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isArbitrator: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    milestoneDispute: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    milestones: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {description: string, amount: bigint, status: bigint, submittedAt: bigint, autoReleasePaused: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseAutoRelease: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    projectCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {client: string, freelancer: string, name: string, description: string, paymentToken: string, totalAmount: bigint, releasedAmount: bigint, milestoneCount: bigint, createdAt: bigint, active: boolean, funded: boolean }],
      'view'
    >
    

    
    registerArbitrator: TypedContractMethod<
      [_arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeArbitrator: TypedContractMethod<
      [_arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestRevision: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitDisputeResponse: TypedContractMethod<
      [_disputeId: BigNumberish, _evidence: string, ],
      [void],
      'nonpayable'
    >
    

    
    submitMilestone: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    triggerAutoRelease: TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    voteOnDispute: TypedContractMethod<
      [_disputeId: BigNumberish, _voteForFreelancer: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'AUTO_RELEASE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DISPUTE_RESPONSE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_ARBITRATORS_PER_DISPUTE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MILESTONES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'arbitratorPool'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'assignArbitrators'): TypedContractMethod<
      [_disputeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autoReleaseTimeRemaining'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'canAutoRelease'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [_freelancer: AddressLike, _name: string, _description: string, _paymentToken: AddressLike, _milestoneDescriptions: string[], _milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositEscrow'): TypedContractMethod<
      [_projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {projectId: bigint, milestoneIndex: bigint, status: bigint, filedBy: string, clientEvidence: string, freelancerEvidence: string, filedAt: bigint, responseDeadline: bigint, votesForFreelancer: bigint, votesForClient: bigint, totalVotes: bigint, outcome: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'enableSponsorship'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'fileDispute'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, _evidence: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getArbitratorPoolSize'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDisputeArbitrators'): TypedContractMethod<
      [_disputeId: BigNumberish, ],
      [[string, string, string]],
      'view'
    >;
getFunction(nameOrSignature: 'getProjectMilestones'): TypedContractMethod<
      [_projectId: BigNumberish, ],
      [GigShield.MilestoneStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isArbitrator'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'milestoneDispute'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'milestones'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {description: string, amount: bigint, status: bigint, submittedAt: bigint, autoReleasePaused: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseAutoRelease'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'projectCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {client: string, freelancer: string, name: string, description: string, paymentToken: string, totalAmount: bigint, releasedAmount: bigint, milestoneCount: bigint, createdAt: bigint, active: boolean, funded: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'registerArbitrator'): TypedContractMethod<
      [_arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeArbitrator'): TypedContractMethod<
      [_arbitrator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRevision'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitDisputeResponse'): TypedContractMethod<
      [_disputeId: BigNumberish, _evidence: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitMilestone'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'triggerAutoRelease'): TypedContractMethod<
      [_projectId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteOnDispute'): TypedContractMethod<
      [_disputeId: BigNumberish, _voteForFreelancer: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ArbitratorRegistered'): TypedContractEvent<ArbitratorRegisteredEvent.InputTuple, ArbitratorRegisteredEvent.OutputTuple, ArbitratorRegisteredEvent.OutputObject>;
getEvent(key: 'ArbitratorRemoved'): TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
getEvent(key: 'ArbitratorVoted'): TypedContractEvent<ArbitratorVotedEvent.InputTuple, ArbitratorVotedEvent.OutputTuple, ArbitratorVotedEvent.OutputObject>;
getEvent(key: 'ArbitratorsAssigned'): TypedContractEvent<ArbitratorsAssignedEvent.InputTuple, ArbitratorsAssignedEvent.OutputTuple, ArbitratorsAssignedEvent.OutputObject>;
getEvent(key: 'AutoReleasePaused'): TypedContractEvent<AutoReleasePausedEvent.InputTuple, AutoReleasePausedEvent.OutputTuple, AutoReleasePausedEvent.OutputObject>;
getEvent(key: 'AutoReleaseTriggered'): TypedContractEvent<AutoReleaseTriggeredEvent.InputTuple, AutoReleaseTriggeredEvent.OutputTuple, AutoReleaseTriggeredEvent.OutputObject>;
getEvent(key: 'DisputeFiled'): TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'DisputeResponseSubmitted'): TypedContractEvent<DisputeResponseSubmittedEvent.InputTuple, DisputeResponseSubmittedEvent.OutputTuple, DisputeResponseSubmittedEvent.OutputObject>;
getEvent(key: 'EscrowDeposited'): TypedContractEvent<EscrowDepositedEvent.InputTuple, EscrowDepositedEvent.OutputTuple, EscrowDepositedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneRevisionRequested'): TypedContractEvent<MilestoneRevisionRequestedEvent.InputTuple, MilestoneRevisionRequestedEvent.OutputTuple, MilestoneRevisionRequestedEvent.OutputObject>;
getEvent(key: 'MilestoneSubmitted'): TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'SponsorshipEnabled'): TypedContractEvent<SponsorshipEnabledEvent.InputTuple, SponsorshipEnabledEvent.OutputTuple, SponsorshipEnabledEvent.OutputObject>;

    filters: {
      
      'ArbitratorRegistered(address)': TypedContractEvent<ArbitratorRegisteredEvent.InputTuple, ArbitratorRegisteredEvent.OutputTuple, ArbitratorRegisteredEvent.OutputObject>;
      ArbitratorRegistered: TypedContractEvent<ArbitratorRegisteredEvent.InputTuple, ArbitratorRegisteredEvent.OutputTuple, ArbitratorRegisteredEvent.OutputObject>;
    

      'ArbitratorRemoved(address)': TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
      ArbitratorRemoved: TypedContractEvent<ArbitratorRemovedEvent.InputTuple, ArbitratorRemovedEvent.OutputTuple, ArbitratorRemovedEvent.OutputObject>;
    

      'ArbitratorVoted(uint256,address)': TypedContractEvent<ArbitratorVotedEvent.InputTuple, ArbitratorVotedEvent.OutputTuple, ArbitratorVotedEvent.OutputObject>;
      ArbitratorVoted: TypedContractEvent<ArbitratorVotedEvent.InputTuple, ArbitratorVotedEvent.OutputTuple, ArbitratorVotedEvent.OutputObject>;
    

      'ArbitratorsAssigned(uint256,address[3])': TypedContractEvent<ArbitratorsAssignedEvent.InputTuple, ArbitratorsAssignedEvent.OutputTuple, ArbitratorsAssignedEvent.OutputObject>;
      ArbitratorsAssigned: TypedContractEvent<ArbitratorsAssignedEvent.InputTuple, ArbitratorsAssignedEvent.OutputTuple, ArbitratorsAssignedEvent.OutputObject>;
    

      'AutoReleasePaused(uint256,uint256)': TypedContractEvent<AutoReleasePausedEvent.InputTuple, AutoReleasePausedEvent.OutputTuple, AutoReleasePausedEvent.OutputObject>;
      AutoReleasePaused: TypedContractEvent<AutoReleasePausedEvent.InputTuple, AutoReleasePausedEvent.OutputTuple, AutoReleasePausedEvent.OutputObject>;
    

      'AutoReleaseTriggered(uint256,uint256,uint256)': TypedContractEvent<AutoReleaseTriggeredEvent.InputTuple, AutoReleaseTriggeredEvent.OutputTuple, AutoReleaseTriggeredEvent.OutputObject>;
      AutoReleaseTriggered: TypedContractEvent<AutoReleaseTriggeredEvent.InputTuple, AutoReleaseTriggeredEvent.OutputTuple, AutoReleaseTriggeredEvent.OutputObject>;
    

      'DisputeFiled(uint256,uint256,uint256,address)': TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
      DisputeFiled: TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint8)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'DisputeResponseSubmitted(uint256,address)': TypedContractEvent<DisputeResponseSubmittedEvent.InputTuple, DisputeResponseSubmittedEvent.OutputTuple, DisputeResponseSubmittedEvent.OutputObject>;
      DisputeResponseSubmitted: TypedContractEvent<DisputeResponseSubmittedEvent.InputTuple, DisputeResponseSubmittedEvent.OutputTuple, DisputeResponseSubmittedEvent.OutputObject>;
    

      'EscrowDeposited(uint256,uint256)': TypedContractEvent<EscrowDepositedEvent.InputTuple, EscrowDepositedEvent.OutputTuple, EscrowDepositedEvent.OutputObject>;
      EscrowDeposited: TypedContractEvent<EscrowDepositedEvent.InputTuple, EscrowDepositedEvent.OutputTuple, EscrowDepositedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneRevisionRequested(uint256,uint256)': TypedContractEvent<MilestoneRevisionRequestedEvent.InputTuple, MilestoneRevisionRequestedEvent.OutputTuple, MilestoneRevisionRequestedEvent.OutputObject>;
      MilestoneRevisionRequested: TypedContractEvent<MilestoneRevisionRequestedEvent.InputTuple, MilestoneRevisionRequestedEvent.OutputTuple, MilestoneRevisionRequestedEvent.OutputObject>;
    

      'MilestoneSubmitted(uint256,uint256)': TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
      MilestoneSubmitted: TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProjectCreated(uint256,address,address,string,uint256)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'SponsorshipEnabled(uint256,uint256)': TypedContractEvent<SponsorshipEnabledEvent.InputTuple, SponsorshipEnabledEvent.OutputTuple, SponsorshipEnabledEvent.OutputObject>;
      SponsorshipEnabled: TypedContractEvent<SponsorshipEnabledEvent.InputTuple, SponsorshipEnabledEvent.OutputTuple, SponsorshipEnabledEvent.OutputObject>;
    
    };
  }