/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ISponsorWhitelistControlInterface extends Interface {
    getFunction(nameOrSignature: "addPrivilegeByAdmin" | "getSponsorForCollateral" | "getSponsorForGas" | "getSponsoredBalanceForCollateral" | "getSponsoredBalanceForGas" | "getSponsoredGasFeeUpperBound" | "isAllWhitelisted" | "isWhitelisted" | "removePrivilegeByAdmin" | "setSponsorForCollateral" | "setSponsorForGas"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addPrivilegeByAdmin', values: [AddressLike, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getSponsorForCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSponsorForGas', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSponsoredBalanceForCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSponsoredBalanceForGas', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSponsoredGasFeeUpperBound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAllWhitelisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isWhitelisted', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removePrivilegeByAdmin', values: [AddressLike, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'setSponsorForCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setSponsorForGas', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addPrivilegeByAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSponsorForCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSponsorForGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSponsoredBalanceForCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSponsoredBalanceForGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSponsoredGasFeeUpperBound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removePrivilegeByAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSponsorForCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSponsorForGas', data: BytesLike): Result;
  }

  

  export interface ISponsorWhitelistControl extends BaseContract {
    
    connect(runner?: ContractRunner | null): ISponsorWhitelistControl;
    waitForDeployment(): Promise<this>;

    interface: ISponsorWhitelistControlInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addPrivilegeByAdmin: TypedContractMethod<
      [contractAddr: AddressLike, addresses: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    getSponsorForCollateral: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [string],
      'view'
    >
    

    
    getSponsorForGas: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [string],
      'view'
    >
    

    
    getSponsoredBalanceForCollateral: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getSponsoredBalanceForGas: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getSponsoredGasFeeUpperBound: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isAllWhitelisted: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isWhitelisted: TypedContractMethod<
      [contractAddr: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    removePrivilegeByAdmin: TypedContractMethod<
      [contractAddr: AddressLike, addresses: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    setSponsorForCollateral: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [void],
      'payable'
    >
    

    
    setSponsorForGas: TypedContractMethod<
      [contractAddr: AddressLike, upperBound: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addPrivilegeByAdmin'): TypedContractMethod<
      [contractAddr: AddressLike, addresses: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getSponsorForCollateral'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSponsorForGas'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSponsoredBalanceForCollateral'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSponsoredBalanceForGas'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSponsoredGasFeeUpperBound'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isAllWhitelisted'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isWhitelisted'): TypedContractMethod<
      [contractAddr: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removePrivilegeByAdmin'): TypedContractMethod<
      [contractAddr: AddressLike, addresses: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSponsorForCollateral'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'setSponsorForGas'): TypedContractMethod<
      [contractAddr: AddressLike, upperBound: BigNumberish, ],
      [void],
      'payable'
    >;

    

    filters: {
      
    };
  }