/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ISponsorWhitelistControlInterface extends Interface {
    getFunction(nameOrSignature: "setSponsorForCollateral" | "setSponsorForGas"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'setSponsorForCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setSponsorForGas', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'setSponsorForCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSponsorForGas', data: BytesLike): Result;
  }

  

  export interface ISponsorWhitelistControl extends BaseContract {
    
    connect(runner?: ContractRunner | null): ISponsorWhitelistControl;
    waitForDeployment(): Promise<this>;

    interface: ISponsorWhitelistControlInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    setSponsorForCollateral: TypedContractMethod<
      [contractAddr: AddressLike, ],
      [void],
      'payable'
    >
    

    
    setSponsorForGas: TypedContractMethod<
      [contractAddr: AddressLike, upperBound: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'setSponsorForCollateral'): TypedContractMethod<
      [contractAddr: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'setSponsorForGas'): TypedContractMethod<
      [contractAddr: AddressLike, upperBound: BigNumberish, ],
      [void],
      'payable'
    >;

    

    filters: {
      
    };
  }